### ISSUE TITLE
Readme Tags have malformed images

### ISSUE THREAD

**Issue by echadwick-wayfair** [KhronosGroup/glTF-Sample-Assets#1]
The Tags section at the start of each README has broken images. The img elements point to readme.md files, which are not image formats.

For example
https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/ABeautifulGame/README.md#tags
Renders as:
```
<a target="_blank" rel="noopener noreferrer" href="/KhronosGroup/glTF-Sample-Assets/blob/main/Models-showcase.md">

<img src="/KhronosGroup/glTF-Sample-Assets/raw/main/Models-showcase.md" alt="showcase" style="max-width: 100%;">

</a>
```

We should consider omitting the img elements entirely, or else setting the URIs to point to actual icon images.

**Comment by DrX3D** [comment]
Resolved with commit [26c6ebf](https://github.com/KhronosGroup/glTF-Sample-Assets/commit/26c6ebfb83b1022ea90a4d5720ee409ca967d46a).

Reran license updates.
