### ISSUE TITLE
Invalid KHR_texture_basisu usage in AnisotropyBarnLamp.gltf

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Sample-Assets#117]
In the `AnisotropyBarnLamp.gltf` sample, the .ktx2 textures are embedded without the required extensions:

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/cfbe2f9ac259490855940ff85feb5b4b02386046/Models/AnisotropyBarnLamp/glTF-KTX-BasisU/AnisotropyBarnLamp.gltf#L312-L333

Compare to the [examples in the spec](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_basisu/README.md#using-without-a-fallback). A quick way to fix this is to read/write the model with glTF Transform, which will automatically append the missing extensions:

```bash
gltf-transform cp input.gltf output.gltf
```

**Comment by echadwick-artist** [comment]
That's what I get for editing raw JSON. Thanks for the issue!
