### ISSUE TITLE
Should this repository be preferred over glTF-Sample-Models for new work?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF-Sample-Assets#12]
I've used glTF-Sample-Models in the past (and continue to do so) for CI and validation of various glTF related tools. However it looks like for some newer extensions the new assets are being added to this repository instead.

I didn't find information about this in the -Models repository so would like to clarify the direction here - is the intention for this repository to basically supersede glTF-Sample-Models, and as such it should replace -Models in the future? Or is the plan for both to coexist?

**Comment by DrX3D** [comment]
This repo is currently in public Beta.  The Working Group is moving towards making this the repo for assets and archiving glTF-Sample-Models. The structure is being tested and improved to make the repo more automatically updated. All new assets (models for now) should be put into this repo. Once all features are present and working in this repo, glTF-Sample-Models will be set to archive.

**Comment by zeux** [comment]
Thanks!
