### ISSUE TITLE
NormalTangentMirrorTest README contains erroneous instructions

### ISSUE THREAD

**Issue by warrenm** [KhronosGroup/glTF-Sample-Assets#120]
The [README](https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/NormalTangentMirrorTest/README.md) for the NormalTangentMirrorTest sample asset contains the following text:

"Note that this model (`NormalTangentTest`) does not supply tangent vectors, and specifically tests a rendering engine's ability to generate the tangent vectors at runtime.  To test supplied tangent vectors, see `NormalTangentMirrorTest`."

It appears that this text was copied from the NormalTangentTest asset unmodified, but it does not apply to NormalTangentMirrorTest (which does, in fact, supply tangents). I feel the two sentences referenced above could be removed, or they could be replaced with other language pertaining to the model's contents.

**Comment by emackey** [comment]
Thanks @warrenm.  The fix for this should be to copy the correct README from the archived repo:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/NormalTangentMirrorTest
