### ISSUE TITLE
Inconsistent folder naming for BasisU assets

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF-Sample-Assets#13]
StainedGlassLamp puts assets into glTF-KTX-BasisU folder, whereas AnisotropyBarnLamp puts them in glTF-KTX2-Basisu (note the 2. and incorrect case on `u`).

It would be nice to match the folder names for all variants for consistency; this helps for tooling that wants to exclude or include folders with a specific name.

**Comment by DrX3D** [comment]
@echadwick-wayfair : Can you address this please.

**Comment by echadwick-wayfair** [comment]
Thanks for catching this! Renamed the folder in this branch: https://github.com/KhronosGroup/glTF-Sample-Assets/pull/3
