### ISSUE TITLE
Clearcoat normal textures used without a tangent space

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Sample-Assets#133]
#### ClearCoatTest
- `/meshes/13/primitives/0/material`

#### TextureTransformMultiTest
- `/meshes/26/primitives/0/material`
- `/meshes/27/primitives/0/material`
- `/meshes/28/primitives/0/material`

**Comment by emackey** [comment]
Related to: https://github.com/KhronosGroup/glTF/pull/2415
