### ISSUE TITLE
Per-vertex color with a decal texture

### ISSUE THREAD

**Issue by limingchina** [KhronosGroup/glTF-Sample-Assets#155]
Is it possible to create a gltf model with per-vertex color covered by a decal texture? The texture has opaque part and transparent part. For the opaque part, it should cover the underlying base color. For the transparent part, the base color shows.

**Comment by echadwick-artist** [comment]
Yes, this is possible. 

Although you would have to use a separate mesh for the decal, make it slightly offset from the vertex color mesh, and use alphaMode:Blend. Here's a quick example.

[VertexColor_Decal.zip](https://github.com/user-attachments/files/17818682/VertexColor_Decal.zip)

![image](https://github.com/user-attachments/assets/daa9c6f5-5224-4c2f-b3b6-9bc125e9bab7)

**Comment by limingchina** [comment]
Thanks for the reply. I'm wondering if I have a big depth range, is the vertex offset good enough to avoid any z-fighting artifacts using this approach.
