### ISSUE TITLE
AttenuationTest is incorrectly tagged with core

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Sample-Assets#16]
The AttenuationTest metadata includes the #core tag and is listed with

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/Models-core.md

However, its description starts with `This model tests interactions between attenuation color, attenuation distance, and thickness in the KHR_materials_volume extension`.

The #core tag should be removed.

**Comment by emackey** [comment]
PR merged.  This should be fixed the next time the readmes are regenerated.  Thanks @andreasplesch.
