### ISSUE TITLE
Sheen test model?

### ISSUE THREAD

**Issue by bhouston** [KhronosGroup/glTF-Sample-Assets#30]
I am noticing sheen differences between renders.  Unfortunately we do not have any test models that show a range of sheen values (sheen, roughness) in a way that can lead people to do an analysis of where they have implementation issues.

I would suggest that we do a classic 4x4 sphere test with sheen?  Along one axis, we range sheen from [0, 0.33, 0.66, 1] and on the other axis we range roughness from [0, 0.33, 0.66, 1].  I would suggest a blue base color.

**Comment by echadwick-artist** [comment]
Done!
