### ISSUE TITLE
Metadata for AnisotropyDiscTest

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Sample-Assets#35]
I added a new model in #32.  But the metadata doesn't seem to have been accepted, and I don't see it in the README.

@DrX3D can you check if I did it wrong?

https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyDiscTest

**Comment by echadwick-artist** [comment]
This looks correct to me. Does this still need work @emackey ?

**Comment by emackey** [comment]
I guess it got fixed at some point.  Thanks.
