### ISSUE TITLE
Confusing folder structure in AnisotropyBarnLamp with two KTX folders

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Sample-Assets#42]
There's what looks like remainders from a previous folder name here:
https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp

<img width="280" alt="image" src="https://github.com/KhronosGroup/glTF-Sample-Assets/assets/2693840/5e1fa0f2-2253-4613-a739-069613d9c00e">

The "glTF-KTX-BasisU" folder seems to be the correct one, the other one and the stray texture inside should probably be deleted.

Side note: this folder rename has also caused https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/503 which doesn't seem to have been updated since the rename happened.

**Comment by DR-xR** [comment]
@echadwick-artist : Please take a look at this. Thanks.

**Comment by echadwick-artist** [comment]
Fixed, thanks for the report.
