### ISSUE TITLE
AnisotropyDiscTest improvement

### ISSUE THREAD

**Issue by elalish** [KhronosGroup/glTF-Sample-Assets#44]
@echadwick-artist Thanks for the test model! However, it's a bit confusing to use because there are sharp transitions in lighting that feel like bugs, but are actually correct given the model's texture:
<img width="810" alt="image" src="https://github.com/KhronosGroup/glTF-Sample-Assets/assets/1649964/630cb414-56cc-4cc0-888b-5d84ca710175">
I would expect that the anisotropy effect is confined to the circles, and hence the square back plates should all look identical, and therefore have no reflection discontinuities between them. However, upon looking at your texture, I see the square backplanes actually have the same anisotropy strength as their circles, but simply a constant direction vector:
<img width="619" alt="image" src="https://github.com/KhronosGroup/glTF-Sample-Assets/assets/1649964/973af2e0-ddb0-4e28-940f-fe6f6c4ab9e1">
Would you mind changing them to all have zero blue channel strength outside of the circle? And ideally make the strength gradient one match: zero outside the same circle, then linearly rising to 1 in the center.

**Comment by echadwick-artist** [comment]
Fixed.
