### ISSUE TITLE
The modelmetadata version should not be included in the LICENSE.md

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Sample-Assets#8]
The [`modelmetadata.php`](https://github.com/KhronosGroup/glTF-Sample-Assets/blob/5279b5271d6bb7985d031460b6b8ecf08caf1c4a/util/modelmetadata.php#L504) currently includes a line in the `LICENSE.md` file of _each_ model that says

> **Generated by modelmetadata 1.0,15-beta**

This means that even the slightest (minor/patch version) update will cause **all** models (i.e. their license files) to count as "modified",  causing [long lists of 'Files Changed'](https://github.com/KhronosGroup/glTF-Sample-Assets/pull/7/files), even when there is no _real_ modification of these files or the models.

This line should **not** be included in the `LICENSE.md` files.

---

I could see a potential reason for including such a line - namely, to emphasize that the files are auto-generated, and should not be modified _manually_ in pull requests, because these manual changes would be overwritten. 

**Iff** such hint should be included, then there could be two acceptable options:

1. Adding it **without a version number**, maybe using `<sub>...</sub>` tags, like
   > License yadda yadda...
   >
   > <sub>This file is auto-generated with `modelmetadata`. Do not modify this file manually.</sub>

2. Adding it **without a version number** as a (HTML) _comment_ inside the markdown, so that is is only visible for those who attempt to edit the file in a text editor. In this case, the comment could also be added at the top of the file, as in
   > ```
   > 
   >
   > License yadda yadda...
   > ```

If this should be included, I'd have a slight preference for the latter, but both could be OK if they don't include the version number.

**Comment by DrX3D** [comment]
What about both. I know it is somewhat redundant, but it does server the purpose of

1. Top HTML comment notifies people who might hand-edit the file
2. Bottom text notifies the readers that the file is auto-generated and presumably current

**Comment by javagl** [comment]
> but both could be OK if they don't include the version number.

Doing _both at the same time_ could also be fine (I don't think that the message for the reader of the MD is sooo important, but am not opposed to including it either)

**Comment by DrX3D** [comment]
Removed version # from all generated files.
